# Generated by Django 4.0.1 on 2022-01-17 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='author/', verbose_name='profile image '),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='post/', verbose_name='thumbnail'),
        ),
    ]
